name: 'Release'
on:
  push:
    branches:
      - 'release'
jobs:
  release:
    if: '!contains(github.event.head_commit.message, ''skip ci'')'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v3'
        with:
          ref: '${{ github.event.pull_request.head.sha }}'
      - name: 'Use Node.js 18.0'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '18.0'
      - name: 'Set up'
        run: |
          yarn install --frozen-lockfile
          yarn setup
      - name: 'Compile'
        run: 'yarn build'
      - name: 'Publish to NPM'
        run: 'yarn release'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
